apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-volume
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{.Values.nfs.path}}
    server: {{.Values.nfs.server}}
  persistentVolumeReclaimPolicy: Retain